/// PawLog Localization System
/// Supports Turkish (tr) and English (en).
/// Default language: Turkish.
///
/// Usage:
///   AppStrings.get('welcome')          // returns translated string
///   AppStrings.setLocale('en')         // switches to English
///   AppStrings.locale                  // current locale code
///   AppStrings.current                 // full active language map

class AppStrings {
  AppStrings._();

  // ──────────────────────────────────────────────
  // Current locale — default is Turkish
  // ──────────────────────────────────────────────
  static String _locale = 'tr';

  static String get locale => _locale;

  static void setLocale(String locale) {
    assert(locale == 'tr' || locale == 'en', 'Unsupported locale: $locale');
    _locale = locale;
  }

  /// Returns the full active language map.
  static Map<String, String> get current => _locale == 'tr' ? _tr : _en;

  /// Returns the translated string for [key].
  /// Falls back to the key itself if not found.
  static String get(String key) => current[key] ?? key;

  // ════════════════════════════════════════════════
  //  TURKISH  🇹🇷
  // ════════════════════════════════════════════════
  static const Map<String, String> _tr = {
    // ── Navigation ────────────────────────────────
    'nav_home': 'Ana Sayfa',
    'nav_record': 'Kayıt',
    'nav_care': 'Bakım',
    'nav_stats': 'İstatistik',
    'nav_learn': 'Öğren',

    // ── Dashboard ─────────────────────────────────
    'welcome': 'PawLog\'a Hoş Geldin!',
    'add_furry_friend': 'Tüylü dostunu ekleyerek başla',
    'add_cat': 'Kedi Ekle',
    'add': 'Ekle',
    'quick_actions': 'Hızlı İşlemler',
    'today_summary': 'Bugünün Özeti',
    'meows': 'MİYAVLAR',
    'no_meows_yet': 'Henüz miyav yok',
    'meows_recorded': 'Miyav Kaydedildi',
    'last': 'Son:',
    'meals_label': 'ÖĞÜNLER',
    'meals_fed': 'Öğün Verildi',
    'no_meals_fed_yet': 'Henüz mama verilmedi',
    'litter_label': 'KUM',
    'not_cleaned_today': 'Bugün temizlenmedi',
    'status_clean': 'Durum: Temiz',
    'checked': 'Kontrol:',
    'record_action': 'Kaydet',
    'fed_action': 'Mama',
    'litter_action': 'Kum',
    'water_action': 'Su',
    'years_old': 'yaşında',
    'months_old': 'aylık',
    'newborn': 'Yeni doğan',
    'yrs': 'yıl',
    'mo': 'ay',

    // ── Record Screen ─────────────────────────────
    'record_meow': 'Miyav Kaydet',
    'meow_button': 'MİYAV!',
    'meow_logged': 'Miyav kaydedildi',
    'intensity': 'Yoğunluk',
    'context': 'Durum',
    'recording': 'Kaydediliyor...',
    'listening': 'Dinleniyor...',
    'start_recording': 'Kaydı başlat',
    'tap_to_start': 'Başlamak için dokun',
    'save_record': 'Kaydı Kaydet',
    'discard': 'İptal',
    'saved': 'Kaydedildi! 🐾',
    'context_label': 'Bağlam',
    'before_meal': 'Mama öncesi',
    'after_play': 'Oyun sonrası',
    'night_time': 'Gece vakti',
    'at_door': 'Kapıda',
    'alone': 'Yalnız',
    'other': 'Diğer',
    'recent_recordings': 'Son Kayıtlar',
    'past_recordings': 'Geçmiş Kayıtlar',
    'no_recordings_yet': 'Henüz miyav kaydı yok.',
    'delete_recording': 'Kaydı Sil? 🗑️',
    'delete_recording_confirm': 'Bu miyav kaydı kalıcı olarak silinecek.',

    // ── Care Screen ───────────────────────────────
    'care': 'Bakım',
    'care_log': 'Bakım Günlüğü',
    'food': 'Mama',
    'water': 'Su',
    'litter': 'Kum',
    'mood': 'Ruh Hali',
    'weight': 'Kilo',
    'log_food': 'Mama Kaydet',
    'log_water': 'Su Kaydet',
    'log_litter_clean': 'Kum Temizliği Kaydet',
    'set_mood': 'Ruh Hali Belirle',
    'log_weight': 'Kilo Kaydet',
    'enter_weight_kg': 'Kiloyu kg olarak gir',
    'update_weight': 'Kiloyu Güncelle ⚖️',
    'today_at': 'Bugün saat',
    'fed': 'Beslendi',
    'refilled': 'Dolduruldu',
    'cleaned': 'Temizlendi',
    'care_history': 'Bakım Geçmişi',
    'no_logs_yet': 'Henüz kayıt yok',
    'kg': 'kg',
    'no_meals_yet': 'Henüz öğün yok',
    'not_refilled_yet': 'Henüz doldurulmadı',
    'last_fed': 'Son mama:',
    'last_refilled': 'Son dolum:',
    'last_cleaned': 'Son temizlik:',
    'history': 'Geçmiş',
    'just_now': 'az önce',
    'd_ago': 'g önce',
    'h_ago': 's önce',
    'm_ago': 'dk önce',
    'delete_log': 'Kaydı Sil?',
    'cannot_be_undone': 'Bu işlem geri alınamaz.',
    'food_history': 'Mama Geçmişi',
    'water_history': 'Su Geçmişi',
    'litter_history': 'Kum Geçmişi',
    'weight_history': 'Kilo Geçmişi',
    'no_food_logs_yet': 'Henüz mama kaydı yok',
    'no_water_logs_yet': 'Henüz su kaydı yok',
    'no_litter_logs_yet': 'Henüz kum kaydı yok',
    'no_weight_logs_yet': 'Henüz kilo kaydı yok',

    // ── Analytics Screen ──────────────────────────
    'analytics': 'Analizler',
    'insights': 'İstatistikler',
    'week': 'Hafta',
    'month': 'Ay',
    'all': 'Tümü',
    'daily_meows': 'Günlük Miyavlar',
    'recordings': 'kayıt',
    'meals': 'öğün',
    'day_streak': 'gün serisi',
    'insight': 'İpucu',
    'feeding_pattern': 'Beslenme düzeni',
    'feeding_timeline': 'Beslenme Zaman Çizelgesi',
    'mood_trend': 'Ruh Hali Eğilimi',
    'mood_trends': 'Ruh hali eğilimi',
    'no_data_yet': 'Henüz veri yok',
    'no_meow_data_yet': 'Henüz miyav verisi yok',
    'no_meals_logged_today': 'Bugün öğün kaydı yok',
    'no_mood_data_yet': 'Henüz ruh hali verisi yok',
    'stats': 'İstatistikler',
    'meows_tooltip': 'miyav',
    'start_recording_insight': 'İstatistik görmek için kayıt yapmaya başla!',
    'record_meows_and_log': 'Miyav kaydet ve bakım aktivitelerini gir',
    'meals_logged_period': 'Bu dönemde kaydedilen öğün',
    'keep_logging_patterns': 'Kalıpları keşfetmek için kayıt yapmaya devam et!',
    'meows_most_morning': 'sabahları en çok miyavlıyor!',
    'meows_most_afternoon': 'öğleden sonra en çok miyavlıyor!',
    'meows_most_evening': 'akşamları en çok miyavlıyor!',
    'had_meals_period': 'bu dönemde öğün yedi',
    'your_cat': 'Kedin',

    // ── Settings Screen ───────────────────────────
    'settings': 'Ayarlar',
    'appearance': 'Görünüm',
    'theme': 'Tema',
    'dark_mode': 'Karanlık Mod',
    'light_mode': 'Aydınlık Mod',
    'playful': 'Oyuncu',
    'modern': 'Modern',
    'about': 'Hakkında',
    'version': 'Sürüm',
    'version_number': 'Sürüm 1.0.0',
    'cat_profile': 'Kedi Profili',
    'edit_profile': 'Profili Düzenle',
    'notifications': 'Bildirimler',
    'language': 'Dil',
    'made_with_love': 'Kedi severler için ❤️ ile yapıldı',

    // ── Cat Form Screen ───────────────────────────
    'edit_cat': 'Kedi Düzenle',
    'name': 'İsim',
    'breed': 'Cins',
    'birth_date': 'Doğum Tarihi',
    'select_date': 'Tarih Seç',
    'gender': 'Cinsiyet',
    'male': 'Erkek',
    'female': 'Dişi',
    'color': 'Renk',
    'save': 'Kaydet',
    'delete': 'Sil',
    'photo': 'Fotoğraf',
    'choose_photo': 'Fotoğraf Seç',
    'camera': 'Kamera',
    'gallery': 'Galeri',
    'tap_to_change_photo': 'Fotoğrafı değiştirmek için dokun',
    'save_changes': 'Değişiklikleri Kaydet 💾',
    'add_cat_button': 'Kedi Ekle 🐾',
    'neutered_spayed': 'Kısırlaştırılmış',
    'weight_kg': 'Kilo (kg)',
    'please_enter_name': 'Lütfen bir isim gir',
    'please_enter_breed': 'Lütfen bir cins gir',
    'please_select_birth_date': 'Lütfen doğum tarihi seç 📅',
    'delete_cat': 'Kediyi Sil? 😿',
    'delete_cat_confirm': 'kediyi silmek istediğine emin misin? Bu işlem geri alınamaz.',
    'are_you_sure_remove': 'silmek istediğine emin misin? Bu işlem geri alınamaz.',

    // ── Onboarding Screen ─────────────────────────
    'onboarding_title_1': 'PawLog\'a\nHoş Geldin!',
    'onboarding_subtitle_1': 'Kedinin tüm ihtiyaçlarını\ntek uygulamadan takip et',
    'onboarding_title_2': 'Miyavlarını\nKaydet',
    'onboarding_subtitle_2': 'Kedinin seslerini kaydet ve\ngünlük aktivitelerini izle',
    'onboarding_title_3': 'Bakımını\nTakip Et',
    'onboarding_subtitle_3': 'Yemek, su, kum ve kilo\ntakibini kolayca yap',
    'skip': 'Atla',
    'next': 'İleri →',
    'get_started': 'Başla! 🐾',

    // ── Training Screen ───────────────────────────
    'training': 'Eğitim',
    'clicker_button': 'Clicker butonu',
    'click': 'Tıkla!',
    'taps': 'tıklama',
    'today': 'bugün',
    'cute_training_plan': 'Eğitim planı',
    'day_streak_label': 'Gün Serisi!',
    'keep_going': 'Devam et!',
    'tap_clicker_to_start': 'Başlamak için clicker\'a dokun!',
    'set_training_progress': 'Eğitim ilerlemesini ayarla',
    'guides': 'Rehberler',
    'read_more': 'Oku →',
    'night_crying': 'Gece ağlaması',
    'scratching': 'Tırmalama',
    'biting': 'Isırma',
    'sit': 'Otur',
    'come': 'Gel',
    'high_five': 'Çak Bir Beşlik',
    'carrier': 'Taşıma Kutusu',

    // ── General ───────────────────────────────────
    'cancel': 'İptal',
    'ok': 'Tamam',
    'yes': 'Evet',
    'no': 'Hayır',
    'error': 'Hata',
    'success': 'Başarılı',
    'confirm': 'Onayla',
    'loading': 'Yükleniyor...',
    'retry': 'Tekrar Dene',
    'close': 'Kapat',
    'search': 'Ara',
    'no_results': 'Sonuç bulunamadı',
    'app_name': 'PawLog',
  };

  // ════════════════════════════════════════════════
  //  ENGLISH  🇬🇧
  // ════════════════════════════════════════════════
  static const Map<String, String> _en = {
    // ── Navigation ────────────────────────────────
    'nav_home': 'Home',
    'nav_record': 'Record',
    'nav_care': 'Care',
    'nav_stats': 'Stats',
    'nav_learn': 'Learn',

    // ── Dashboard ─────────────────────────────────
    'welcome': 'Welcome to PawLog!',
    'add_furry_friend': 'Add your furry friend to get started.',
    'add_cat': 'Add Cat',
    'add': 'Add',
    'quick_actions': 'Quick Actions',
    'today_summary': 'Today Summary',
    'meows': 'MEOWS',
    'no_meows_yet': 'No meows yet',
    'meows_recorded': 'Meows Recorded',
    'last': 'Last:',
    'meals_label': 'MEALS',
    'meals_fed': 'Meals Fed',
    'no_meals_fed_yet': 'No meals fed yet',
    'litter_label': 'LITTER',
    'not_cleaned_today': 'Not cleaned today',
    'status_clean': 'Status: Clean',
    'checked': 'Checked:',
    'record_action': 'Record',
    'fed_action': 'Fed',
    'litter_action': 'Litter',
    'water_action': 'Water',
    'years_old': 'years old',
    'months_old': 'months old',
    'newborn': 'Newborn',
    'yrs': 'yrs',
    'mo': 'mo',

    // ── Record Screen ─────────────────────────────
    'record_meow': 'Record Meow',
    'meow_button': 'MEOW!',
    'meow_logged': 'Meow logged',
    'intensity': 'Intensity',
    'context': 'Context',
    'recording': 'Recording...',
    'listening': 'Listening...',
    'start_recording': 'Start recording',
    'tap_to_start': 'Tap to start',
    'save_record': 'Save Record',
    'discard': 'Discard',
    'saved': 'Saved! 🐾',
    'context_label': 'Context',
    'before_meal': 'Before meal',
    'after_play': 'After play',
    'night_time': 'Night time',
    'at_door': 'At door',
    'alone': 'Alone',
    'other': 'Other',
    'recent_recordings': 'Recent recordings',
    'past_recordings': 'Past Recordings',
    'no_recordings_yet': 'No meows recorded yet.',
    'delete_recording': 'Delete Recording? 🗑️',
    'delete_recording_confirm': 'This will permanently delete this meow recording.',

    // ── Care Screen ───────────────────────────────
    'care': 'Care',
    'care_log': 'Care Log',
    'food': 'Food',
    'water': 'Water',
    'litter': 'Litter',
    'mood': 'Mood',
    'weight': 'Weight',
    'log_food': 'Log Food',
    'log_water': 'Log Water',
    'log_litter_clean': 'Log Litter Clean',
    'set_mood': 'Set Mood',
    'log_weight': 'Log Weight',
    'enter_weight_kg': 'Enter weight in kg',
    'update_weight': 'Update Weight ⚖️',
    'today_at': 'Today at',
    'fed': 'Fed',
    'refilled': 'Refilled',
    'cleaned': 'Cleaned',
    'care_history': 'Care History',
    'no_logs_yet': 'No logs yet',
    'kg': 'kg',
    'no_meals_yet': 'No meals yet',
    'not_refilled_yet': 'Not refilled yet',
    'last_fed': 'Last fed:',
    'last_refilled': 'Last refilled:',
    'last_cleaned': 'Last cleaned:',
    'history': 'History',
    'just_now': 'just now',
    'd_ago': 'd ago',
    'h_ago': 'h ago',
    'm_ago': 'm ago',
    'delete_log': 'Delete Log?',
    'cannot_be_undone': 'This cannot be undone.',
    'food_history': 'Food History',
    'water_history': 'Water History',
    'litter_history': 'Litter History',
    'weight_history': 'Weight History',
    'no_food_logs_yet': 'No Food logs yet',
    'no_water_logs_yet': 'No Water logs yet',
    'no_litter_logs_yet': 'No Litter logs yet',
    'no_weight_logs_yet': 'No Weight logs yet',

    // ── Analytics Screen ──────────────────────────
    'analytics': 'Analytics',
    'insights': 'Insights',
    'week': 'Week',
    'month': 'Month',
    'all': 'All',
    'daily_meows': 'Daily Meows',
    'recordings': 'recordings',
    'meals': 'meals',
    'day_streak': 'day streak',
    'insight': 'Insight',
    'feeding_pattern': 'Feeding pattern',
    'feeding_timeline': 'Feeding Timeline',
    'mood_trend': 'Mood Trend',
    'mood_trends': 'Mood trends',
    'no_data_yet': 'No data yet',
    'no_meow_data_yet': 'No meow data yet',
    'no_meals_logged_today': 'No meals logged today',
    'no_mood_data_yet': 'No mood data yet',
    'stats': 'Stats',
    'meows_tooltip': 'meows',
    'start_recording_insight': 'Start recording to see insights!',
    'record_meows_and_log': 'Record meows and log care activities',
    'meals_logged_period': 'meals logged this period',
    'keep_logging_patterns': 'Keep logging to discover patterns!',
    'meows_most_morning': 'meows most in the morning!',
    'meows_most_afternoon': 'meows most in the afternoon!',
    'meows_most_evening': 'meows most in the evening!',
    'had_meals_period': 'had meals this period',
    'your_cat': 'Your cat',

    // ── Settings Screen ───────────────────────────
    'settings': 'Settings',
    'appearance': 'Appearance',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'playful': 'Playful',
    'modern': 'Modern',
    'about': 'About',
    'version': 'Version',
    'version_number': 'Version 1.0.0',
    'cat_profile': 'Cat Profile',
    'edit_profile': 'Edit Profile',
    'notifications': 'Notifications',
    'language': 'Language',
    'made_with_love': 'Made with ❤️ for cat lovers',

    // ── Cat Form Screen ───────────────────────────
    'edit_cat': 'Edit Cat',
    'name': 'Name',
    'breed': 'Breed',
    'birth_date': 'Birth Date',
    'select_date': 'Select Date',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'color': 'Color',
    'save': 'Save',
    'delete': 'Delete',
    'photo': 'Photo',
    'choose_photo': 'Choose Photo',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'tap_to_change_photo': 'Tap to change photo',
    'save_changes': 'Save Changes 💾',
    'add_cat_button': 'Add Cat 🐾',
    'neutered_spayed': 'Neutered/Spayed',
    'weight_kg': 'Weight (kg)',
    'please_enter_name': 'Please enter a name',
    'please_enter_breed': 'Please enter a breed',
    'please_select_birth_date': 'Please select a birth date 📅',
    'delete_cat': 'Delete Cat? 😿',
    'delete_cat_confirm': 'Are you sure you want to remove this cat? This action cannot be undone.',
    'are_you_sure_remove': 'Are you sure you want to remove? This action cannot be undone.',

    // ── Onboarding Screen ─────────────────────────
    'onboarding_title_1': 'Welcome to\nPawLog!',
    'onboarding_subtitle_1': 'Track all your cat\'s needs\nfrom one app',
    'onboarding_title_2': 'Record\nMeows',
    'onboarding_subtitle_2': 'Record your cat\'s sounds and\ntrack daily activities',
    'onboarding_title_3': 'Track\nCare',
    'onboarding_subtitle_3': 'Easily track food, water,\nlitter and weight',
    'skip': 'Skip',
    'next': 'Next →',
    'get_started': 'Get Started! 🐾',

    // ── Training Screen ───────────────────────────
    'training': 'Training',
    'clicker_button': 'Clicker button',
    'click': 'Click!',
    'taps': 'taps',
    'today': 'today',
    'cute_training_plan': 'Cute training plan',
    'day_streak_label': 'Day Streak!',
    'keep_going': 'Keep going!',
    'tap_clicker_to_start': 'Tap the clicker to start!',
    'set_training_progress': 'Set training progress',
    'guides': 'Guides',
    'read_more': 'Read →',
    'night_crying': 'Night crying',
    'scratching': 'Scratching',
    'biting': 'Biting',
    'sit': 'Sit',
    'come': 'Come',
    'high_five': 'High Five',
    'carrier': 'Carrier',

    // ── General ───────────────────────────────────
    'cancel': 'Cancel',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'error': 'Error',
    'success': 'Success',
    'confirm': 'Confirm',
    'loading': 'Loading...',
    'retry': 'Retry',
    'close': 'Close',
    'search': 'Search',
    'no_results': 'No results found',
    'app_name': 'PawLog',
  };
}
